# Generated by Django 4.1.1 on 2022-10-06 05:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='book_list',
            new_name='album_list',
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=50)),
                ('publish_date', models.DateField(verbose_name='publish date')),
                ('genre', models.CharField(max_length=50)),
                ('summary', models.TextField(max_length=500)),
                ('track_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None)),
                ('profile', models.ManyToManyField(to='main_app.profile')),
            ],
        ),
    ]
