# Generated by Django 4.1.1 on 2022-10-06 05:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_profile_album_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='track_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, null=True, size=None),
        ),
    ]
