# Generated by Django 4.1.2 on 2022-10-12 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_rename_album_profile_albums'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='album_list',
        ),
    ]
