# Generated by Django 4.1.2 on 2022-10-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_album_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='publish_date',
            field=models.CharField(max_length=50),
        ),
    ]
